### PR TITLE
Add WV VBM esign

### PR DESCRIPTION
**Pull request by amyrlam**
Story: https://app.clubhouse.io/turnout2020/story/1448/wv-vbm-esign

### CODE REVIEW

**Comment by amyrlam** [comment]
Tests passed, but couldn't get the pdf email to work, same question as: https://github.com/vote/turnout/pull/289

@benweissmann I wasn't sure if was too short on some of the checkbox abbreviations?

**Comment by amyrlam** [comment]
I solved ^^, here is the pdf, seems to look good?

[200719.Le8B4ib1h.wv-weissmann-ballotrequest.pdf](https://github.com/vote/turnout/files/4945380/200719.Le8B4ib1h.wv-weissmann-ballotrequest.pdf)

- [ ] Question: I noticed the cover page of this pdf and the one on https://github.com/vote/turnout/pull/289 says Miami, is that ok?

**Comment by benweissmann** [comment]
This is a great start! West Virginia is an esign state, though, so you'll also need to configure `form_fields` to let the user fill out all the other part of the form (for esign states, we submit the completed form directly to the user's local election official -- the user never has to download or print the PDF).

Check out the "YAML configuration for esign states" section of the notion doc, or this PR as an example: https://github.com/vote/turnout/pull/288

I'm hoping to get Debra's review on this tonight so if you don't have time to take another pass on that no worries! Just let me know by 2pm eastern so I can take a pass on it before that review session tonight.

**Comment by benweissmann** [comment]
Oh and the Miami thing on the cover page is just because the `region` in the sample `curl` command is for Miami -- when you test it out using the frontend, it'll pick the right region for the user's address.

**Comment by benweissmann** [comment]
Notes:
- WV has a mandatory excuse
- Only the general is coming up
- I omitted the excuse for incarceration, because it requires the sheriff, chief of police, or deputy to sign the second page
- I omitted the address confidentiality option because it requires mailing to form to the SOS instead of the LEO
- I did not include the name/address update option; WV has OVR so voters can use that

State PDF (two pages):

Screen Shot 2020-07-20 at 4 44 48 PM

Screen Shot 2020-07-20 at 4 44 57 PM


Our form, default state:

Screen Shot 2020-07-20 at 4 43 37 PM


Our form, filled out:

Screen Shot 2020-07-20 at 4 43 50 PM


Signature page:

Screen Shot 2020-07-20 at 4 44 24 PM

**Comment by amyrlam** [comment]
Thanks @benweissmann for finishing this!

**Pull request merged**
