### PR TITLE
Django Admin: State election information

### PR DESCRIPTION
**Pull request by ericisaiah**
https://app.clubhouse.io/turnout2020/story/5572/enable-voteamerica-staff-to-edit-all-data-currently-editable-in-manage-in-manage-admin

### CODE REVIEW

**Comment by ericisaiah** [comment]
@benweissmann Would you mind taking an early look at this given your understanding of the existing management front-end? This is configuring the django admin for task 1: "State information: https://admin.voteamerica.com/manage/election/state/ (and https://admin.voteamerica.com/manage/election/fieldinformationtype/ which is the same info but grouped differently)"

(I'm ignoring any build failures for now.)

**Comment by benweissmann** [comment]
This looks good to me. A couple notes of important features we added or relied on with the current admin tool that we should make sure to preserve:

- State information field types can have "help text", and we show this help text on the page where you edit the value for a particular state. For example, see [this help text for `vbm_voted_ballot_deadline_mail`](https://admin.voteamerica.com/manage/election/state/AK/vbm_voted_ballot_deadline_mail/?ref=fieldinformationtype). This was really important for providing instructions to the research team (in this case, that `vbm_voted_ballot_deadline_mail` needs to start with "Postmarked by" or "Received by").

- Having markdown preview on the edit pages was pretty important -- before we added that, we had a lot of broken markdown that didn't render correctly on the site.

- It's important to have some way to view all the info for one particular field type across all states (e.g. [this page](https://admin.voteamerica.com/manage/election/fieldinformationtype/vbm_voted_ballot_deadline_mail/)). This was useful to do things like make sure the wording for a field is consistent across states, or spot-check that a new field is fully filled out and ready to be displayed before we start using it on the site. We can probably do this with filters in the django admin?

- We have an edit log of who editing this info and when, added recently on Debra's request. See https://admin.voteamerica.com/manage/election/state/AL/vbm_voted_ballot_deadline_mail/?ref=fieldinformationtype for an example.

**Comment by ericisaiah** [comment]
@benweissmann would you mind taking another look at this? (I'll squash before merging.) In particular, please take a close look at the model changes and flag anything you think might affect the API. The admin changes I'm less worried about.

**Review by benweissmann — APPROVED** [review]
Looks great!

**Comment by ericisaiah** [comment]
Thanks!

**Pull request merged**
